### ISSUE TITLE
RColor is not defined

### ISSUE THREAD

**Issue by nekollx** [sterlingwes/RandomColor#4]
probably just me but might help someone else.
So i imported the rcolor.js into my node project but when i call
```
var color = new RColor;
var c2 = color.get(true);

```

i get a fatal error that breaks my program

RColor is not defined

the rcolor.js is in the same directory as the function I'm calling, so its not a nesting issue it just doesn't reconize it.

**Comment by sterlingwes** [comment]
I should probably make it a proper node module... 4 years and overdue!

Assuming you're doing something like `var RColor = require('./rcolor')` it should work fine.

**Comment by sterlingwes** [comment]
Now on [NPM](https://npmjs.com/package/rcolor)
