### ISSUE TITLE
Color proximity

### ISSUE THREAD

**Issue by sterlingwes** [sterlingwes/RandomColor#5]
This library often generates colours that are too close in proximity to others in a series. Should add some maths to account for this and ensure a certain amount of differentiation within a certain sample size.

For reference: http://www.brucelindbloom.com/index.html?Equations.html

**Comment by aparshin** [comment]
@sterlingwes First of all, thank you for the nice library!

I think that you have a bug/issue in sources: every time the main function is called without `hue`, you take a random value and adds `goldenRatio`, which is pretty much random number with the same distribution. Instead, in the [original article](https://martin.ankerl.com/2009/12/09/how-to-create-random-colors-programmatically/), the random number was generated only once followed by multiple additions of `goldenRatio` (it will give you a _sequence_ of distributed "semi-random" colors.

BTW, if the `hue` is set in parameters, you shouldn't modify it and use as is (at least if I understand semantic correctly).

**Comment by sterlingwes** [comment]
@aparshin you're absolutely right, thank you for the feedback 🙏 

I believe I've addressed your comment in the referenced PR, but let me know if I've missed the mark

**Comment by aparshin** [comment]
@sterlingwes Looks great! Thank you for the fix!
